#!/bin/bash

# set radio mode and frequency
#rigctl -m 124 -r /dev/ttyUSB0 M RTTYR 0
#rigctl -m 124 -r /dev/ttyUSB0 F 10101150

# start modem and display
minimodem 50 -S 1514 -M 1964 -i -5 --stopbits 1.5 -q 
